baseURL = 'https://data-visualization.jp/'
languageCode = 'ja'
title = 'Data Visualization Japan'
theme = 'stack'

[params]
  mainSections = ['posts']

  [params.colorScheme]
    toggle = true
    default = 'dark'

  [params.sidebar]
    subtitle = 'データビジュアライゼーションのコミュニティです'

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = 'img/logo.png'

  [params.widgets]

  [[params.widgets.homepage]]
    type = 'categories'

    [params.widgets.homepage.params]
      limit = 10

  [[params.widgets.homepage]]
    type = 'tag-cloud'

    [params.widgets.homepage.params]
      limit = 15

  [[params.widgets.page]]
    type = 'categories'

    [params.widgets.page.params]
      limit = 10

  [[params.widgets.page]]
    type = 'tag-cloud'

    [params.widgets.page.params]
      limit = 15

[permalinks]
  posts = '/:slug/'
