baseURL = 'https://data-visualization.jp/'
languageCode = 'ja-jp'
title = 'Data Visualization Japan'
theme = 'stack'

[params]
  mainSections = ['posts']

  [params.colorScheme]
    toggle = true
    default = 'dark'

  [params.sidebar]
    subtitle = 'データビジュアライゼーションのコミュニティです'

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = 'img/logo.png'

  [params.widgets]

  [[params.widgets.homepage]]
    type = 'categories'

    [params.widgets.homepage.params]
      limit = 10

  [[params.widgets.homepage]]
    type = 'tag-cloud'

    [params.widgets.homepage.params]
      limit = 15

  [[params.widgets.page]]
    type = 'categories'

    [params.widgets.page.params]
      limit = 10

  [[params.widgets.page]]
    type = 'tag-cloud'

    [params.widgets.page.params]
      limit = 15

[menu]

  [[menu.main]]
    identifier = 'home'
    name = 'トップ'
    url = '/'
    weight = 10

    [menu.main.params]
      icon = 'home'

  [[menu.main]]
    identifier = 'search'
    name = '検索'
    url = '/search/'
    weight = 20

    [menu.main.params]
      icon = 'search'

  [[menu.main]]
    identifier = 'posts'
    name = '記事一覧'
    url = '/posts/'
    weight = 30

    [menu.main.params]
      icon = 'messages'

  [[menu.main]]
    identifier = 'categories'
    name = 'カテゴリー'
    url = '/categories/'
    weight = 40

    [menu.main.params]
      icon = 'categories'

  [[menu.main]]
    identifier = 'tags'
    name = 'タグ'
    url = '/tags/'
    weight = 50

    [menu.main.params]
      icon = 'tag'

[permalinks]
  posts = '/:slug/'
